firesim_gemmini_rerocc_pairmanager_dummy8x8_2c6p6_sbus64_nic_hwdebug:
    PLATFORM: f2
    TARGET_PROJECT: firesim
    TARGET_PROJECT_MAKEFRAG: ../../../generators/firechip/chip/src/main/makefrag/firesim
    DESIGN: FireSim
    TARGET_CONFIG: FireSimGemminiReRoCCPairDummy8x8C2P6Sbus64NICDebugConfig
    PLATFORM_CONFIG: WithTargetCycleDebug_WithPrintfSynthesis_WithSynthAsserts_FRFCFS16GBQuadRank_BaseF2Config
    deploy_quintuplet: null
    platform_config_args:
        fpga_frequency: 20
        build_strategy: TIMING
    post_build_hook: null
    metasim_customruntimeconfig: null
    bit_builder_recipe: bit-builder-recipes/f2.yaml
